name: vqvae-tpm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - _openmp_mutex
  - libstdcxx
  - libsodium
  - packaging
  - six
  - wcwidth
  - matplotlib-inline
  - ca-certificates
  - comm
  - typing_extensions
  - libuuid
  - jedi
  - jupyter_core
  - prompt-toolkit
  - libnsl
  - pyzmq
  - _libgcc_mutex
  - readline
  - zipp
  - ptyprocess
  - setuptools
  - libgomp
  - exceptiongroup
  - jupyter_client
  - libgcc-ng
  - libgcc
  - pip
  - parso
  - pickleshare
  - traitlets
  - libstdcxx-ng
  - python-dateutil
  - ld_impl_linux-64
  - nest-asyncio
  - tk
  - krb5
  - libffi
  - libzlib
  - decorator
  - pygments
  - debugpy
  - executing
  - tornado
  - ncurses
  - bzip2
  - openssl
  - importlib-metadata
  - pure_eval
  - stack_data
  - asttokens
  - ipython
  - wheel
  - libedit
  - psutil
  - zeromq
  - tzdata
  - pexpect
  - platformdirs
  - ipykernel
  - pandas
  - pygraphviz

